language: python

addons:
    apt:
        packages:
        - npm
        - asciidoctor

#before_install:

install:
    - sudo npm install -g firebase
    - wget https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - pip install Pygments

script:
    - hugo
    - firebase deploy --token $FIREBASE_TOKEN

#after_success: |
