language: python
sudo: required

addons:
    apt:
        packages:
        - asciidoctor

before_install:
    - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
    - apt-get install -y nodejs
    - npm install -g firebase

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.deb
    - dpkg -i hugo*.deb
    - pip install Pygments

script:
    - hugo

after_success:
    - firebase deploy --token $FIREBASE_TOKEN
        
