steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['submodule', 'update', '--init', '--recursive']
- name: 'gcr.io/$PROJECT_ID/hugo'
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy --token $$FIREBASE_TOKEN']
  secretEnv: ['FIREBASE_TOKEN']

# Encrypt Github token for push changes
secrets:
- kmsKeyName: projects/directed-advice-162422/locations/global/keyRings/blog/cryptoKeys/firebase-token
  secretEnv:
    FIREBASE_TOKEN: CiQA5dRPRgD04jJ0bUfUvHJEYgNrS8a/lbpRCZHSflJ4V7z18k8SVgDwWP36ljtDWP0QnH+lwse+YbaAGLiDYmMke0S4ZMrJyrKH51l1uQViEDtHEgrv8TgbX6q8/ZJnwfdTKv2l3olA3JXUVF2l8scZjOcgE5rf374FbZp0
