baseurl: 'https://blog.kenthua.com/'
title: tech ramblings
copyright: >-
  Content posted here do not reflect the views of any commerical or
  organizational entity, they are of my opinion and mine only.
canonifyURLs: true
relativeURLs: true
theme: beautifulhugo
paginate: 10
summaryLength: 30
enableEmoji: true
pygmentsCodeFences: true
pygmentsUseClasses: true
pygmentsCodefencesGuessSyntax: true
enableRobotsTXT: true
enableGitInfo: true
disqusShortname: techramblings
googleAnalytics: UA-80183602-1

permalinks:
  post: '/:year/:month/:day/:filename/'
  code: '/:filename/'

author:
  name: Kent Hua
  github: kenthua
  gitlab: kenthua
  linkedin: kenthua
  facebook: ''
  twitter: kent_hua
  instagram: ''
params:
  subtitle: 'cloud, open source, home automation, technology'
  rss: true
  comments: true
  dateFormat: '2006-01-02'
  readingTime: true
  socialShare: true
  useHLJS: true
  description: 'Discussion about technology and things that interest me'
  keywords: 'cloud,open source,home automation,technology,gcp,gke,kubernetes,java,google,tech'
menu:
  main:
    - name: Home
      url: /
      weight: 0
    - name: Blog
      url: /post/
      weight: 10
