baseurl: 'https://blog.kenthua.com/'
title: 'Tech Ramblings'
copyright: >-
  Content posted here do not reflect the views of any commerical or
  organizational entity, they are of my opinion and mine only.

canonifyURLs: true
relativeURLs: true
uglyURLs: false
theme: hugo-bootstrap-premium
paginate: 10
summaryLength: 30
enableEmoji: true
#pygmentsCodeFences: true
enableRobotsTXT: true
enableGitInfo: true
disqusShortname: techramblings
googleAnalytics: UA-80183602-1

permalinks:
  post: '/:year/:month/:day/:filename/'
  code: '/:filename/'

author:
  name: Kent Hua
  github: kenthua
  gitlab: kenthua
  linkedin: kenthua
  facebook: ''
  twitter: kent_hua
  instagram: ''
params:
  tagline: 'cloud, open source, home automation, technology'
  bootswatchtheme: 'paper' #hbp
  showRightSidebar: 'true' #hbp
  googleAnalytics: 'UA-80183602-1' #hbp
  showBlogHeader: true #hbp
  switchlang: false #hbp
menu:
  main:
    - name: Home
      url: /
      weight: 0
    - name: Blog
      url: /post/
      weight: 10
